### ISSUE TITLE
Shamelessly copy for Phosphor?

### ISSUE THREAD

**Issue by noozo** [mveytsman/heroicons_elixir#10]
Hi Max, thanks for this great library!

Is it ok if i fork it and adapt to use Phosphor instead of Heroicons? Also, can i later publish it on hex?

Thanks again!
Pedro

**Comment by noozo** [comment]
Hope you don't mind, but i went ahead and built it. 

As a side note which might affect you in the future:

Since Phosphoricons include 1047 icons (Heroicons are only 230) i hit some weird dynamic function count limit on the erlang VM. So i decided to make some changes and generate packages per letter prefixing the icon (for instance the `alarm` icon will live under the `Bold.A` package. If Heroicons ever gets to 1024+ icons you will probably have the same issue :)

https://hex.pm/packages/phosphoricons

**Comment by mveytsman** [comment]
Happy to see forks and more projects.

Is this function limit because the functions are generated via a macro or can you not have a module with more than 1024 functions?

I think that a future direction for this project (and perhaps your fork!) is to statically generate the code and download the icons, and have a task to update them - so we can tie package version to heroicon version. See https://github.com/mveytsman/heroicons_elixir/issues/6 for some discussion on it

**Comment by noozo** [comment]
Yeah, that would be helpful. I don't know what is the limit, but the error is something like this:
```
Compiling 2 files (.ex)

== Compilation error in file lib/phosphoricons.ex ==
** (CompileError) elixir_compiler_2:1: function '__MODULE__'/1+13:
  An implementation limit was reached.
  Try reducing the complexity of this function.

  Instruction: {call_ext,4,{extfunc,'Elixir.Module','__put_attribute__',4}}

    (stdlib 3.16.1) lists.erl:1342: :lists.foreach/2
```

Maybe you can shed some more light on it :)

**Comment by tcoopman** [comment]
@noozo I just did a test:

```elixir
defmodule Generator do
  defmacro __using__(_opts) do
    quote do
      defmodule Generated do
        for i <- Enum.to_list(1..2000) do
          name = "name_#{i}"

          quote do
            def unquote(name)() do
              nil
            end
          end
        end
      end
    end
  end
end
```

This compiles fine, so I guess it's not just that limit that you're running into
